In [27]:
from ucimlrepo import fetch_ucirepo

import pandas as pd

In [37]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
heart_disease = fetch_ucirepo(id=45) 
  
# data (as pandas dataframes) 
X = heart_disease.data.features 
y = heart_disease.data.targets 
  
# # metadata 
# print(heart_disease.metadata) 
  
# # variable information 
# print(heart_disease.variables) 

print(heart_disease.head())

TypeError: 'NoneType' object is not callable

In [28]:
# 파일은 new.data 데이터 사용
main_data = pd.read_table("..\\data\\heart_disease\\processed.cleveland.data")
main_data

    63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
0    67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5...
1    67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6...
2    37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5...
3    41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4...
4    56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8...
..                                                 ...
297  45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2...
298  68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4...
299  57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2...
300  57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0...
301  38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0...

[302 rows x 1 columns]

In [29]:
main_data.head()

  63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
0  67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5...
1  67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6...
2  37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5...
3  41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4...
4  56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8...

In [30]:
main_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 1 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0  302 non-null    str
dtypes: str(1)
memory usage: 2.5 KB

In [33]:
main_data.describe()

       63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
count                                                 302
unique                                                302
top     67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5...
freq                                                    1

---

In [ ]:
main